<div class="page-sidebar-wrapper">
		<div class="page-sidebar navbar-collapse collapse">
 			<ul class="page-sidebar-menu " data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200">
				<li class="start active open">
					<a href="javascript:;">
					<i class="icon-home"></i>
					<span class="title">Dashboard</span>
					<span class="selected"></span>
					<span class="arrow open"></span>
					</a>
				</li>
				<li class="start">
					<a href="javascript:;">
					<i class="icon-home"></i>
					<span class="title">Menu</span>
					<span class="selected"></span>
					<span class="arrow open"></span>
					</a>
				</li>
				<li class="start">
					<a href="javascript:;">
					<i class="icon-home"></i>
					<span class="title">Message</span>
					<span class="selected"></span>
					<span class="arrow open"></span>
					</a>
				</li>
				<li class="start">
					<a href="javascript:;">
					<i class="icon-home"></i>
					<span class="title">Account</span>
					<span class="selected"></span>
					<span class="arrow open"></span>
					</a>
				</li>
			</ul>
			<!-- END SIDEBAR MENU -->
		</div>
	</div>