<?php echo $this->doctype(); ?>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en" class="no-js">
<!--<![endif]-->
<!-- BEGIN HEAD -->
<head>

<?php echo $this->headTitle($this->translate('Homecooker'))->setSeparator(' - ')->setAutoEscape(false) ?>

<?php echo $this->headMeta()
    ->appendName('viewport', 'width=device-width, initial-scale=1')
    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
?>
<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css"/>
<!-- Le styles -->
<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath('assets/global/plugins/font-awesome/css/font-awesome.min.css'))
                ->prependStylesheet($this->basePath('assets/global/plugins/simple-line-icons/simple-line-icons.min.css'))
                ->prependStylesheet($this->basePath('assets/global/plugins/bootstrap/css/bootstrap.min.css')) 
                ->prependStylesheet($this->basePath('assets/global/plugins/uniform/css/uniform.default.css')) 
                ->prependStylesheet($this->basePath('assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css'))
                ->prependStylesheet($this->basePath('assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.css')) 
                ->prependStylesheet($this->basePath('assets/admin/pages/css/profile.css')) 
                ->prependStylesheet($this->basePath('assets/admin/pages/css/tasks.css')) 
                /*->prependStylesheet($this->basePath('assets/global/plugins/bootstrap-daterangepicker/daterangepicker-bs3.css')) 
                ->prependStylesheet($this->basePath('assets/global/plugins/fullcalendar/fullcalendar.min.css')) 
                ->prependStylesheet($this->basePath('assets/global/plugins/jqvmap/jqvmap/jqvmap.css')) */

                ->prependStylesheet($this->basePath('assets/global/css/components.css')) 
                ->prependStylesheet($this->basePath('assets/global/css/plugins.css')) 
                ->prependStylesheet($this->basePath('assets/admin/layout/css/layout.css')) 
                ->prependStylesheet($this->basePath('assets/admin/layout/css/themes/darkblue.css')) 
                ->prependStylesheet($this->basePath('assets/admin/layout/css/custom.css'))           						
?>

<!-- Scripts -->
<?php echo $this->headScript()
    ->prependFile($this->basePath('js/bootstrap.min.js'))
    ->prependFile($this->basePath('js/jquery.min.js'))
    ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
    ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
; ?>

</head>

<body class="page-header-fixed page-quick-sidebar-over-content page-sidebar-closed-hide-logo page-container-bg-solid">
	<div class="page-header navbar navbar-fixed-top">
        <!-- BEGIN HEADER INNER -->
        <div class="page-header-inner">
            <!-- BEGIN LOGO -->
            <div class="page-logo">
                <a href="index.html">
                    <img src="<?php echo $this->basePath('assets/admin/layout/img/logo.png') ?>" alt="logo" class="logo-default"/>
                </a>
                <div class="menu-toggler sidebar-toggler hide"></div>
			</div>
			<!-- END LOGO -->

            <!-- BEGIN RESPONSIVE MENU TOGGLER -->
            <a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse">
            </a>
			<!-- END RESPONSIVE MENU TOGGLER -->

			<!-- BEGIN TOP NAVIGATION MENU -->
			<div class="top-menu">
				<ul class="nav navbar-nav pull-right">
                    <li class="dropdown dropdown-extended dropdown-notification" id="header_notification_bar">
                        <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                            <i class="icon-bell"></i>
                            <span class="badge badge-default">7 </span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="external">
                                <h3><span class="bold">12 pending</span> notifications</h3>
                                <a href="extra_profile.html">view all</a>
                            </li>
                            <li>
                                <ul class="dropdown-menu-list scroller" style="height: 250px;" data-handle-color="#637283">
                                    <li>
                                        <a href="javascript:;">
                                        <span class="time">just now</span>
                                        <span class="details">
                                        <span class="label label-sm label-icon label-success">
                                        <i class="fa fa-plus"></i>
                                        </span>New user registered. </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="javascript:;">
                                        <span class="time">3 mins</span>
                                        <span class="details">
                                        <span class="label label-sm label-icon label-danger">
                                        <i class="fa fa-bolt"></i>
                                        </span>Server #12 overloaded. </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="javascript:;">
                                        <span class="time">10 mins</span>
                                        <span class="details">
                                        <span class="label label-sm label-icon label-warning">
                                        <i class="fa fa-bell-o"></i>
                                        </span>Server #2 not responding. </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="javascript:;">
                                        <span class="time">14 hrs</span>
                                        <span class="details">
                                        <span class="label label-sm label-icon label-info">
                                        <i class="fa fa-bullhorn"></i>
                                        </span>Application error. </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="javascript:;">
                                        <span class="time">2 days</span>
                                        <span class="details">
                                        <span class="label label-sm label-icon label-danger">
                                        <i class="fa fa-bolt"></i>
                                        </span>Database overloaded 68%. </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="javascript:;">
                                        <span class="time">3 days</span>
                                        <span class="details">
                                        <span class="label label-sm label-icon label-danger">
                                        <i class="fa fa-bolt"></i>
                                        </span>A user IP blocked. </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="javascript:;">
                                        <span class="time">4 days</span>
                                        <span class="details">
                                        <span class="label label-sm label-icon label-warning">
                                        <i class="fa fa-bell-o"></i>
                                        </span>Storage Server #4 not responding dfdfdfd. </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="javascript:;">
                                        <span class="time">5 days</span>
                                        <span class="details">
                                        <span class="label label-sm label-icon label-info">
                                        <i class="fa fa-bullhorn"></i>
                                        </span>System Error. </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="javascript:;">
                                        <span class="time">9 days</span>
                                        <span class="details">
                                        <span class="label label-sm label-icon label-danger">
                                        <i class="fa fa-bolt"></i>
                                        </span>Storage server failed. </span>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                    <!-- END NOTIFICATION DROPDOWN -->

                    <!-- BEGIN INBOX DROPDOWN -->
                    <li class="dropdown dropdown-extended dropdown-inbox" id="header_inbox_bar">
                        <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                            <i class="icon-envelope-open"></i>
                            <span class="badge badge-default">4 </span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="external">
                                <h3>You have <span class="bold">7 New</span> Messages</h3>
                                <a href="page_inbox.html">view all</a>
                            </li>
                            <li>
                                <ul class="dropdown-menu-list scroller" style="height: 275px;" data-handle-color="#637283">
                                    <li>
                                        <a href="inbox.html?a=view">
                                        <span class="photo">
                                        <img src="<?php echo $this->basePath('assets/admin/layout3/img/avatar2.jpg') ?>" class="img-circle" alt="">
                                        </span>
                                        <span class="subject">
                                        <span class="from">
                                        Lisa Wong </span>
                                        <span class="time">Just Now </span>
                                        </span>
                                        <span class="message">
                                        Vivamus sed auctor nibh congue nibh. auctor nibh auctor nibh... </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="inbox.html?a=view">
                                        <span class="photo">
                                        <img src="<?php echo $this->basePath('assets/admin/layout3/img/avatar3.jpg') ?>" class="img-circle" alt="">
                                        </span>
                                        <span class="subject">
                                        <span class="from">
                                        Richard Doe </span>
                                        <span class="time">16 mins </span>
                                        </span>
                                        <span class="message">
                                        Vivamus sed congue nibh auctor nibh congue nibh. auctor nibh auctor nibh... </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="inbox.html?a=view">
                                        <span class="photo">
                                        <img src="<?php echo $this->basePath('assets/admin/layout3/img/avatar1.jpg') ?>" class="img-circle" alt="">
                                        </span>
                                        <span class="subject">
                                        <span class="from">
                                        Bob Nilson </span>
                                        <span class="time">2 hrs </span>
                                        </span>
                                        <span class="message">
                                        Vivamus sed nibh auctor nibh congue nibh. auctor nibh auctor nibh... </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="inbox.html?a=view">
                                        <span class="photo">
                                        <img src="<?php echo $this->basePath('assets/admin/layout3/img/avatar2.jpg') ?>" class="img-circle" alt="">
                                        </span>
                                        <span class="subject">
                                        <span class="from">
                                        Lisa Wong </span>
                                        <span class="time">40 mins </span>
                                        </span>
                                        <span class="message">
                                        Vivamus sed auctor 40% nibh congue nibh... </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="inbox.html?a=view">
                                        <span class="photo">
                                        <img src="<?php echo $this->basePath('assets/admin/layout3/img/avatar3.jpg') ?>" class="img-circle" alt="">
                                        </span>
                                        <span class="subject">
                                        <span class="from">
                                        Richard Doe </span>
                                        <span class="time">46 mins </span>
                                        </span>
                                        <span class="message">
                                        Vivamus sed congue nibh auctor nibh congue nibh. auctor nibh auctor nibh... </span>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                    <!-- END INBOX DROPDOWN -->
                    <!-- BEGIN TODO DROPDOWN -->
                    <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
                    <li class="dropdown dropdown-extended dropdown-tasks" id="header_task_bar">
                        <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                        <i class="icon-calendar"></i>
                        <span class="badge badge-default">3 </span>
                        </a>
                        <ul class="dropdown-menu extended tasks">
                            <li class="external">
                                <h3>You have <span class="bold">12 pending</span> tasks</h3>
                                <a href="page_todo.html">view all</a>
                            </li>
                            <li>
                                <ul class="dropdown-menu-list scroller" style="height: 275px;" data-handle-color="#637283">
                                    <li>
                                        <a href="javascript:;">
                                        <span class="task">
                                        <span class="desc">New release v1.2 </span>
                                        <span class="percent">30%</span>
                                        </span>
                                        <span class="progress">
                                        <span style="width: 40%;" class="progress-bar progress-bar-success" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100"><span class="sr-only">40% Complete</span></span>
                                        </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="javascript:;">
                                        <span class="task">
                                        <span class="desc">Application deployment</span>
                                        <span class="percent">65%</span>
                                        </span>
                                        <span class="progress">
                                        <span style="width: 65%;" class="progress-bar progress-bar-danger" aria-valuenow="65" aria-valuemin="0" aria-valuemax="100"><span class="sr-only">65% Complete</span></span>
                                        </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="javascript:;">
                                        <span class="task">
                                        <span class="desc">Mobile app release</span>
                                        <span class="percent">98%</span>
                                        </span>
                                        <span class="progress">
                                        <span style="width: 98%;" class="progress-bar progress-bar-success" aria-valuenow="98" aria-valuemin="0" aria-valuemax="100"><span class="sr-only">98% Complete</span></span>
                                        </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="javascript:;">
                                        <span class="task">
                                        <span class="desc">Database migration</span>
                                        <span class="percent">10%</span>
                                        </span>
                                        <span class="progress">
                                        <span style="width: 10%;" class="progress-bar progress-bar-warning" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100"><span class="sr-only">10% Complete</span></span>
                                        </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="javascript:;">
                                        <span class="task">
                                        <span class="desc">Web server upgrade</span>
                                        <span class="percent">58%</span>
                                        </span>
                                        <span class="progress">
                                        <span style="width: 58%;" class="progress-bar progress-bar-info" aria-valuenow="58" aria-valuemin="0" aria-valuemax="100"><span class="sr-only">58% Complete</span></span>
                                        </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="javascript:;">
                                        <span class="task">
                                        <span class="desc">Mobile development</span>
                                        <span class="percent">85%</span>
                                        </span>
                                        <span class="progress">
                                        <span style="width: 85%;" class="progress-bar progress-bar-success" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100"><span class="sr-only">85% Complete</span></span>
                                        </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="javascript:;">
                                        <span class="task">
                                        <span class="desc">New UI release</span>
                                        <span class="percent">38%</span>
                                        </span>
                                        <span class="progress progress-striped">
                                        <span style="width: 38%;" class="progress-bar progress-bar-important" aria-valuenow="18" aria-valuemin="0" aria-valuemax="100"><span class="sr-only">38% Complete</span></span>
                                        </span>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                    <!-- END TODO DROPDOWN -->
                    <!-- BEGIN USER LOGIN DROPDOWN -->
                    <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
                    <li class="dropdown dropdown-user">
                        <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                            <img alt="" class="img-circle" src="<?php echo $this->basePath('assets/admin/layout/img/avatar3_small.jpg') ?>"/>
                            <span class="username username-hide-on-mobile">Nick </span>
                            <i class="fa fa-angle-down"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-default">
                            <li>
                                <a href="extra_profile.html">
                                <i class="icon-user"></i> My Profile </a>
                            </li>
                            <li>
                                <a href="page_calendar.html">
                                <i class="icon-calendar"></i> My Calendar </a>
                            </li>
                            <li>
                                <a href="inbox.html">
                                <i class="icon-envelope-open"></i> My Inbox <span class="badge badge-danger">
                                3 </span>
                                </a>
                            </li>
                            <li>
                                <a href="page_todo.html">
                                <i class="icon-rocket"></i> My Tasks <span class="badge badge-success">
                                7 </span>
                                </a>
                            </li>
                            <li class="divider">
                            </li>
                            <li>
                                <a href="extra_lock.html">
                                <i class="icon-lock"></i> Lock Screen </a>
                            </li>
                            <li>
                                <a href="login.html">
                                <i class="icon-key"></i> Log Out </a>
                            </li>
                        </ul>
                    </li>
                    <!-- END USER LOGIN DROPDOWN -->
                    <!-- BEGIN QUICK SIDEBAR TOGGLER -->
                    <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
                    <li class="dropdown dropdown-quick-sidebar-toggler">
                        <a href="javascript:;" class="dropdown-toggle">
                        <i class="icon-logout"></i>
                        </a>
                    </li>
                    <!-- END QUICK SIDEBAR TOGGLER -->
                </ul>
            </div>
            <!-- END TOP NAVIGATION MENU -->
        </div>
        <!-- END HEADER INNER -->
    </div>
	<!--end the Header section -->
    
    <div class="clearfix"></div>
	<!-- BEGIN CONTAINER -->
    <div class="page-container">
    	<!--Sidebar Start-->
        <div class="page-sidebar-wrapper">
	        <div class="page-sidebar navbar-collapse collapse">
    	        <ul class="page-sidebar-menu page-sidebar-menu-closed" data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200">
                <li class="sidebar-search-wrapper">
                    <form class="sidebar-search sidebar-search-bordered" action="extra_search.html" method="POST">
                        <a href="javascript:;" class="remove">
                        <i class="icon-close"></i>
                        </a>
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Search...">
                            <span class="input-group-btn">
                            <a href="javascript:;" class="btn submit"><i class="icon-magnifier"></i></a>
                            </span>
                        </div>
                    </form>
                    <!-- END RESPONSIVE QUICK SEARCH FORM -->
                </li>
                <li class="start active open">
                    <a href="javascript:;">
                    <i class="icon-home"></i>
                    <span class="title">Dashboard</span>
                    <span class="arrow "></span>
                    </a>
                    <ul class="sub-menu">
                        <li>
                            <a href="index.html">
                            <i class="icon-bar-chart"></i>
                            Default Dashboard</a>
                        </li>
                        <li>
                            <a href="index_2.html">
                            <i class="icon-bulb"></i>
                            New Dashboard #1</a>
                        </li>
                        <li>
                            <a href="index_3.html">
                            <i class="icon-graph"></i>
                            New Dashboard #2</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="javascript:;">
                    <i class="icon-basket"></i>
                    <span class="title">eCommerce</span>
                    <span class="arrow "></span>
                    </a>
                    <ul class="sub-menu">
                        <li>
                            <a href="ecommerce_index.html">
                            <i class="icon-home"></i>
                            Dashboard</a>
                        </li>
                        <li>
                            <a href="ecommerce_orders.html">
                            <i class="icon-basket"></i>
                            Orders</a>
                        </li>
                        <li>
                            <a href="ecommerce_orders_view.html">
                            <i class="icon-tag"></i>
                            Order View</a>
                        </li>
                        <li>
                            <a href="ecommerce_products.html">
                            <i class="icon-handbag"></i>
                            Products</a>
                        </li>
                        <li>
                            <a href="ecommerce_products_edit.html">
                            <i class="icon-pencil"></i>
                            Product Edit</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="javascript:;">
                    <i class="icon-rocket"></i>
                    <span class="title">Page Layouts</span>
                    <span class="arrow "></span>
                    </a>
                    <ul class="sub-menu">
                        <li>
                            <a href="layout_horizontal_sidebar_menu.html">
                            Horizontal & Sidebar Menu</a>
                        </li>
                        <li>
                            <a href="index_horizontal_menu.html">
                            Dashboard & Mega Menu</a>
                        </li>
                        <li>
                            <a href="layout_horizontal_menu1.html">
                            Horizontal Mega Menu 1</a>
                        </li>
                        <li>
                            <a href="layout_horizontal_menu2.html">
                            Horizontal Mega Menu 2</a>
                        </li>
                        <li>
                            <a href="layout_fontawesome_icons.html">
                            <span class="badge badge-roundless badge-danger">new</span>Layout with Fontawesome Icons</a>
                        </li>
                        <li>
                            <a href="layout_glyphicons.html">
                            Layout with Glyphicon</a>
                        </li>
                        <li>
                            <a href="layout_full_height_portlet.html">
                            <span class="badge badge-roundless badge-success">new</span>Full Height Portlet</a>
                        </li>
                        <li>
                            <a href="layout_full_height_content.html">
                            <span class="badge badge-roundless badge-warning">new</span>Full Height Content</a>
                        </li>
                        <li>
                            <a href="layout_search_on_header1.html">
                            Search Box On Header 1</a>
                        </li>
                        <li>
                            <a href="layout_search_on_header2.html">
                            Search Box On Header 2</a>
                        </li>
                        <li>
                            <a href="layout_sidebar_search_option1.html">
                            Sidebar Search Option 1</a>
                        </li>
                        <li>
                            <a href="layout_sidebar_search_option2.html">
                            Sidebar Search Option 2</a>
                        </li>
                        <li>
                            <a href="layout_sidebar_reversed.html">
                            <span class="badge badge-roundless badge-warning">new</span>Right Sidebar Page</a>
                        </li>
                        <li>
                            <a href="layout_sidebar_fixed.html">
                            Sidebar Fixed Page</a>
                        </li>
                        <li>
                            <a href="layout_sidebar_closed.html">
                            Sidebar Closed Page</a>
                        </li>
                        <li>
                            <a href="layout_ajax.html">
                            Content Loading via Ajax</a>
                        </li>
                        <li>
                            <a href="layout_disabled_menu.html">
                            Disabled Menu Links</a>
                        </li>
                        <li>
                            <a href="layout_blank_page.html">
                            Blank Page</a>
                        </li>
                        <li>
                            <a href="layout_boxed_page.html">
                            Boxed Page</a>
                        </li>
                        <li>
                            <a href="layout_language_bar.html">
                            Language Switch Bar</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="javascript:;">
                    <i class="icon-diamond"></i>
                    <span class="title">UI Features</span>
                    <span class="arrow "></span>
                    </a>
                    <ul class="sub-menu">
                        <li>
                            <a href="ui_general.html">
                            General Components</a>
                        </li>
                        <li>
                            <a href="ui_buttons.html">
                            Buttons</a>
                        </li>
                        <li>
                            <a href="ui_confirmations.html">
                            Popover Confirmations</a>
                        </li>
                        <li>
                            <a href="ui_icons.html">
                            <span class="badge badge-roundless badge-danger">new</span>Font Icons</a>
                        </li>
                        <li>
                            <a href="ui_colors.html">
                            Flat UI Colors</a>
                        </li>
                        <li>
                            <a href="ui_typography.html">
                            Typography</a>
                        </li>
                        <li>
                            <a href="ui_tabs_accordions_navs.html">
                            Tabs, Accordions & Navs</a>
                        </li>
                        <li>
                            <a href="ui_tree.html">
                            <span class="badge badge-roundless badge-danger">new</span>Tree View</a>
                        </li>
                        <li>
                            <a href="ui_page_progress_style_1.html">
                            <span class="badge badge-roundless badge-warning">new</span>Page Progress Bar</a>
                        </li>
                        <li>
                            <a href="ui_blockui.html">
                            Block UI</a>
                        </li>
                        <li>
                            <a href="ui_bootstrap_growl.html">
                            <span class="badge badge-roundless badge-warning">new</span>Bootstrap Growl Notifications</a>
                        </li>
                        <li>
                            <a href="ui_notific8.html">
                            Notific8 Notifications</a>
                        </li>
                        <li>
                            <a href="ui_toastr.html">
                            Toastr Notifications</a>
                        </li>
                        <li>
                            <a href="ui_alert_dialog_api.html">
                            <span class="badge badge-roundless badge-danger">new</span>Alerts & Dialogs API</a>
                        </li>
                        <li>
                            <a href="ui_session_timeout.html">
                            Session Timeout</a>
                        </li>
                        <li>
                            <a href="ui_idle_timeout.html">
                            User Idle Timeout</a>
                        </li>
                        <li>
                            <a href="ui_modals.html">
                            Modals</a>
                        </li>
                        <li>
                            <a href="ui_extended_modals.html">
                            Extended Modals</a>
                        </li>
                        <li>
                            <a href="ui_tiles.html">
                            Tiles</a>
                        </li>
                        <li>
                            <a href="ui_datepaginator.html">
                            <span class="badge badge-roundless badge-success">new</span>Date Paginator</a>
                        </li>
                        <li>
                            <a href="ui_nestable.html">
                            Nestable List</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="javascript:;">
                    <i class="icon-puzzle"></i>
                    <span class="title">UI Components</span>
                    <span class="arrow "></span>
                    </a>
                    <ul class="sub-menu">
                        <li>
                            <a href="components_pickers.html">
                            Date & Time Pickers</a>
                        </li>
                        <li>
                            <a href="components_context_menu.html">
                            Context Menu</a>
                        </li>
                        <li>
                            <a href="components_dropdowns.html">
                            Custom Dropdowns</a>
                        </li>
                        <li>
                            <a href="components_form_tools.html">
                            Form Widgets & Tools</a>
                        </li>
                        <li>
                            <a href="components_form_tools2.html">
                            Form Widgets & Tools 2</a>
                        </li>
                        <li>
                            <a href="components_editors.html">
                            Markdown & WYSIWYG Editors</a>
                        </li>
                        <li>
                            <a href="components_ion_sliders.html">
                            Ion Range Sliders</a>
                        </li>
                        <li>
                            <a href="components_noui_sliders.html">
                            NoUI Range Sliders</a>
                        </li>
                        <li>
                            <a href="components_jqueryui_sliders.html">
                            jQuery UI Sliders</a>
                        </li>
                        <li>
                            <a href="components_knob_dials.html">
                            Knob Circle Dials</a>
                        </li>
                    </ul>
                </li>
            </ul>
            	<!-- END SIDEBAR MENU -->
        	</div>
    	</div>
        <!--End the Sidebar -->
        
        <!-- Body Content here -->
        <?php echo $this->content; ?>
        <!-- End Body here -->

	</div>
    <!--End Container -->
    
    <!-- BEGIN FOOTER -->
    <div class="page-footer">
        <div class="page-footer-inner">
             2014 &copy; Metronic by keenthemes. <a href="http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes" title="Purchase Metronic just for 27$ and get lifetime updates for free" target="_blank">Purchase Metronic!</a>
        </div>
        <div class="scroll-to-top">
            <i class="icon-arrow-up"></i>
        </div>
    </div>
    <!-- END FOOTER section -->

<!-- Scripts -->
<?php echo $this->headScript()
    ->prependFile($this->basePath('assets/global/plugins/jquery.min.js'))
    ->prependFile($this->basePath('assets/global/plugins/jquery-migrate.min.js'))
    ->prependFile($this->basePath('assets/global/plugins/jquery-ui/jquery-ui.min.js'))
    ->prependFile($this->basePath('assets/global/plugins/bootstrap/js/bootstrap.min.js'))

    ->prependFile($this->basePath('assets/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js'))
    ->prependFile($this->basePath('assets/global/plugins/jquery-slimscroll/jquery.slimscroll.js'))
    ->prependFile($this->basePath('assets/global/plugins/jquery.blockui.min.js'))
    ->prependFile($this->basePath('assets/global/plugins/jquery.cokie.min.js'))

    ->prependFile($this->basePath('assets/global/plugins/uniform/jquery.uniform.min.js'))
    ->prependFile($this->basePath('assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js'))
    /*->prependFile($this->basePath('assets/global/plugins/jqvmap/jqvmap/jquery.vmap.js'))
    ->prependFile($this->basePath('assets/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.russia.js'))

    ->prependFile($this->basePath('assets/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.world.js'))
    ->prependFile($this->basePath('assets/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.europe.js'))
    ->prependFile($this->basePath('assets/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.germany.js'))
    ->prependFile($this->basePath('assets/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.usa.js'))

    ->prependFile($this->basePath('assets/global/plugins/jqvmap/jqvmap/data/jquery.vmap.sampledata.js'))
    ->prependFile($this->basePath('assets/global/plugins/flot/jquery.flot.min.js'))
    ->prependFile($this->basePath('assets/global/plugins/flot/jquery.flot.resize.min.js'))
    ->prependFile($this->basePath('assets/global/plugins/flot/jquery.flot.categories.min.js'))

    ->prependFile($this->basePath('assets/global/plugins/jquery.pulsate.min.js'))
    ->prependFile($this->basePath('assets/global/plugins/bootstrap-daterangepicker/moment.min.js'))
    ->prependFile($this->basePath('assets/global/plugins/bootstrap-daterangepicker/daterangepicker.js'))
    ->prependFile($this->basePath('assets/global/plugins/fullcalendar/fullcalendar.min.js'))*/

    ->prependFile($this->basePath('assets/global/plugins/jquery-easypiechart/jquery.easypiechart.min.js'))
    ->prependFile($this->basePath('assets/global/plugins/jquery.sparkline.min.js'))

    ->prependFile($this->basePath('assets/global/scripts/metronic.js'))
    ->prependFile($this->basePath('assets/admin/layout/scripts/layout.js'))
    ->prependFile($this->basePath('assets/admin/layout/scripts/quick-sidebar.js'))
    ->prependFile($this->basePath('assets/admin/layout/scripts/demo.js'))
    ->prependFile($this->basePath('assets/admin/pages/scripts/index.js'))
    ->prependFile($this->basePath('assets/admin/pages/scripts/tasks.js'))
; ?>

<script>
jQuery(document).ready(function() {       
   // initiate layout and plugins
   Metronic.init(); // init metronic core components
Layout.init(); // init current layout
QuickSidebar.init(); // init quick sidebar
Demo.init(); // init demo features
Profile.init(); // init page demo
});
</script>
<!-- END JAVASCRIPTS -->
</body>
<!-- END BODY -->
</html>
